[build]
  command = "pip install -r requirements.txt && python"
  publish = "static"
  
[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
